vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.smarttab = true
vim.opt.cindent = true
vim.opt.wrap = true
vim.opt.guicursor = "i:block"
vim.cmd("set path+=**")
